name: "🛠 Hardware Issue"
description: "Report issues related to hardware"
title: "[Hardware]"
labels: ["hardware"]
body:
  - type: markdown
    attributes:
      value: |
        **Describe the Hardware Issue**
        Provide a clear and concise description of the hardware-related issue.

  - type: input
    id: hardware_details
    attributes:
      label: "Hardware Details"
      description: "Include details such as device model and version."
      placeholder: "e.g., Device Model, Hardware Version"
  
  - type: textarea
    id: reproduction_steps
    attributes:
      label: "Steps to Reproduce"
      description: "Provide steps to reproduce the issue."
  
  - type: textarea
    id: expected_behavior
    attributes:
      label: "Expected Behavior"
      description: "What you expected to happen."
  
  - type: textarea
    id: additional_context
    attributes:
      label: "Additional Context"
      description: "Any other information about the problem."