name: "🔒 Security Issue"
description: "Report a potential security vulnerability"
title: "[Security]"
labels: ["security"]
body:
  - type: markdown
    attributes:
      value: |
        **Describe the Security Issue**
        Provide a summary of the potential security vulnerability.

  - type: textarea
    id: reproduction_steps
    attributes:
      label: "Steps to Reproduce"
      description: "How to reproduce the issue, if applicable."
  
  - type: dropdown
    id: severity_level
    attributes:
      label: "Severity Level"
      options:
        - Low
        - Medium
        - High
        - Critical
  
  - type: textarea
    id: potential_impact
    attributes:
      label: "Potential Impact"
      description: "Possible impact of this issue on the project."
  
  - type: textarea
    id: additional_context
    attributes:
      label: "Additional Context"
      description: "Any other information to aid in the investigation."